image: java:1.8.0-jdk

stages:
  - prepare
  - track
  - check
  - build
  - test
  - export

java-version:
  stage: prepare
  script:
    # Checking Java version + Directories
    - readlink -f $(which java)
    - java -version
  retry: 1

gradle-version:
  stage: prepare
  script:
    # Checking Gradle version
    - gradle -version
  retry: 1

set-paths:
  stage: prepare
  script:
    # Setting JAVA and Gradle to the default path
    - export PATH=$PATH:/opt/gradle/gradle-4.2.1/bin
    - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
    - export PATH=$PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin

code-count:
  stage: track
  script:
    - ls -las
    #
    # Calculate .java count
    - echo '|Lines |Words |Chars' > java_tracker.txt
    - git ls-files | grep "\(.java\)$" | xargs wc -cwl
    - git ls-files | grep "\(.java\)$" | xargs wc -cwl >> java_tracker.txt
    #
    # Calculate with coverage
    - cloc core
    - cloc core > adv_java_tracker.txt
    - cloc desktop
    - cloc desktop >> adv_java_tracker.txt
    - cloc . --by-file-by-lang
    - cloc . --by-file-by-lang > all_adv_java_tracker.txt
    #
    # Calculate .gradle count
    #- echo '|Lines |Words |Chars' > gradle_tracker.txt
    - git ls-files | grep "\(.gradle\)$" | xargs wc -cwl
    #- git ls-files | grep "\(.gradle\)$" | xargs wc -cwl >> gradle_tracker.txt
    #
    # Lists all assets
    - git ls-files > assets_list.txt
    #
    # Keep the development graph line
    - git log --graph --full-history --all --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"
    #- git log --graph --full-history --all --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s" > logs.txt
    #
    # Check directory again
    - mkdir trackers
    - mv *.txt trackers/
    - ls -las
  artifacts:
    expire_in: 30 day
    paths:
    - trackers
  allow_failure: true
  retry: 1
  only:
    - master
    - develop

gradle-check:
  stage: check
  script:
    # Gradle check for correct dependency imports
    - gradle check
  retry: 1

gradle-tasks:
  stage: check
  script:
    # Gives out lists of Gradle Tasks
    - gradle -q tasks
  retry: 1

gradle-clean:
  stage: check
  script:
    # Deletes previous build cache
    - gradle clean
  retry: 1

build-game:
  stage: build
  script:
    # Pretty much like compiling the files
    - gradle assemble

run-game:
  stage: test
  script:
    # Do gradle check and gradle assemble
    - gradle run
  retry: 1
