image: java:1.8.0-jdk

stages:
  - prepare
  - check
  - build
  - test
  - track

java-version:
  stage: prepare
  script:
    # Checking Java version + Directories
    - java -version
    - readlink -f $(which java)
  retry: 1

gradle-version:
  stage: prepare
  script:
    # Checking Gradle version
    - gradle -version
  retry: 1

set-paths:
  stage: prepare
  script:
    - export PATH=$PATH:/opt/gradle/gradle-4.2.1/bin
    - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
    - export PATH=$PATH:/usr/lib/jvm/java-8-openjdk/bin
  only:
    - web

gradle-check:
  stage: check
  script:
    # Gradle check for correct dependency imports
    - gradle check

gradle-tasks:
  stage: check
  script:
    # Gives out lists of Gradle Tasks
    - gradle -q tasks

gradle-clean:
  stage: check
  script:
    # Deletes previous build cache
    - gradle clean

build-game:
  stage: build
  script:
    # Pretty much like compiling the files
    - gradle assemble
  only:
    - develop
    - master
    - /^feature.*$/

run-game:
  stage: test
  script:
    # Do gradle check and gradle assemble
    - gradle run
  only:
    - develop
    - master
    - /^feature.*$/

code-count:
  stage: track
  script:
    - ls -las
    #
    # Calculate .java count
    - echo '|Lines |Words |Chars' > java_tracker.txt
    - git ls-files | grep "\(.java\)$" | xargs wc -cwl >> java_tracker.txt
    #
    # Calculate with coverage
    - cloc core > adv_java_tracker.txt
    - cloc desktop >> adv_java_tracker.txt
    - cloc $(git ls-files) > all_adv_java_tracker.txt
    #
    # Calculate .gradle count
    - echo '|Lines |Words |Chars' > gradle_tracker.txt
    - git ls-files | grep "\(.gradle\)$" | xargs wc -cwl >> gradle_tracker.txt
    #
    # Calculate photo count
    - echo '|Lines |Words |Chars' > photo_tracker.txt
    - git ls-files | grep "\(.png\|.jpg\|.jpeg\|.gif\|.svg\)$" | xargs wc -c >> photo_tracker.txt
    #
    # Lists all assets
    - git ls-files > assets_list.txt
    #
    # Keep the development graph line
    - git log --decorate --oneline --graph > logs.txt
    #
    # Check directory again
    - mkdir trackers
    - mv *.txt trackers/
    - ls -las
  artifacts:
    expire_in: 1 month
    paths: 
    - trackers

