image: java:1.8.0-jdk

stages:
  - prepare
  - check
  - build
  - test
# - export

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
#  - export GRADLE_USER_HOME=`pwd`/.gradle

java-version:
  stage: prepare
  script:
    # Checking Java version + Directories
    - java -version
    - readlink -f $(which java)
  retry: 1

gradle-version:
  stage: prepare
  script:
    # Checking Gradle version
    - gradle -version
  retry: 1

gradle-check:
  stage: check
  script:
    # Gradle check for correct dependency imports
    - gradle check

gradle-tasks:
  stage: check
  script:
    # Gives out lists of Gradle Tasks
    - gradle -q tasks

gradle-clean:
  stage: check
  script:
    # Deletes previous build cache
    - gradle clean

build-game:
  stage: build
  script:
    # Pretty much like compiling the files
    - gradle assemble

run-game:
  stage: test
  script:
    # Do gradle check and gradle assemble
    - gradle run

#export-game:
#  stage: export
#  script:
#    - gradle fatJar
#  artifacts:
#    paths:
#      - $project/build/libs/
#    expire_in: 5 day
#  allow_failure: true
#  retry: 1
